//! robots.txt support (opt-in via `--respect-robots`).
//!
//! Scope: RFC 9309 longest-match `Allow`/`Disallow` evaluation, including the
//! `*` and `$` wildcard characters, over the request **path + query** (a
//! query-only `Disallow: /*?download=` now actually applies — it used to be
//! silently ignored because only `Url::path()` was checked).
//!
//! Group handling follows RFC 9309 §2.1: consecutive `User-agent:` lines form
//! one group whose rules apply to every listed token. (The previous
//! implementation tracked a single "am I in the wildcard group" flag that the
//! *next* `User-agent:` line — even a more specific one in the same block —
//! would silently clear, so `User-agent: *` followed by `User-agent: SomeBot`
//! lost the wildcard rules entirely.) Evaluation prefers a group whose token
//! matches webseek's own identity (see [`PRODUCT_TOKEN`]) over the `*` group,
//! per RFC 9309 §2.2.1.
//!
//! Not implemented: `Crawl-delay` (webseek's own rate limiter already paces
//! requests) and `Sitemap:` (irrelevant to a fetcher). This is a
//! from-scratch parser, not a full BNF-conformance implementation — comments
//! and whitespace are handled, but pathological inputs are not fuzz-tested.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use url::Url;

use crate::error::{Error, Result};
use crate::http::{Http, MAX_ROBOTS_BYTES};
use crate::ratelimit;

/// The token webseek looks for in `User-agent:` lines, distinct from the
/// browser-like string sent in the HTTP `User-Agent` header. Sites that
/// specifically target "webseek" (or a case-insensitive variant) get their
/// own group honored instead of always falling back to `*`.
pub const PRODUCT_TOKEN: &str = "webseek";

#[derive(Debug, Clone, Default)]
struct Group {
    /// Lower-cased product tokens this group applies to (`*` included as-is).
    agents: Vec<String>,
    /// `(pattern, is_allow)` in file order; longest match wins, `Allow` wins
    /// ties (RFC 9309 §2.2.2).
    rules: Vec<(String, bool)>,
}

impl Group {
    fn applies_to(&self, token: &str) -> bool {
        self.agents.iter().any(|a| a == token)
    }
}

/// Longest-match decision across every rule in every given group. Real
/// robots.txt files commonly repeat a `User-agent: *` (or any other) block
/// more than once, interleaved with other groups — e.g. generated by
/// appending a plugin's rules to a hand-written file — and crawlers are
/// expected to apply the union of all matching groups' rules, not just
/// whichever one happens to appear first. `Allow` wins ties (RFC 9309
/// §2.2.2).
fn decide(groups: &[&Group], target: &str) -> bool {
    let mut best: Option<(usize, bool)> = None;
    for group in groups {
        for (pattern, is_allow) in &group.rules {
            if !matches_pattern(pattern, target) {
                continue;
            }
            let len = pattern.len();
            best = match best {
                Some((blen, ballow)) if blen > len || (blen == len && !*is_allow && ballow) => {
                    Some((blen, ballow))
                }
                _ => Some((len, *is_allow)),
            };
        }
    }
    best.map(|(_, allow)| allow).unwrap_or(true)
}

/// Parsed robots.txt, independent of any particular crawler identity.
#[derive(Debug, Clone, Default)]
pub struct RobotsDoc {
    groups: Vec<Group>,
}

impl RobotsDoc {
    /// Is fetching `path_and_query` permitted for `product`?
    ///
    /// Prefers the most specific matching groups (`product`, case-insensitive)
    /// and only falls back to `*` groups when none exist — a site that wrote
    /// rules specifically for us is not overridden by a looser wildcard block
    /// placed elsewhere in the file. *Every* group matching the winning
    /// token is merged (see [`decide`]), not just the first one found.
    pub fn is_allowed(&self, product: &str, path_and_query: &str) -> bool {
        let product = product.to_ascii_lowercase();
        let specific: Vec<&Group> = self
            .groups
            .iter()
            .filter(|g| g.applies_to(&product))
            .collect();
        if !specific.is_empty() {
            return decide(&specific, path_and_query);
        }
        let wildcard: Vec<&Group> = self.groups.iter().filter(|g| g.applies_to("*")).collect();
        if wildcard.is_empty() {
            return true; // no applicable group at all -> unrestricted
        }
        decide(&wildcard, path_and_query)
    }
}

/// Parse a robots.txt body. Pure and testable; comments (`#` to end of line)
/// are stripped before any other processing.
pub fn parse_robots(body: &str) -> RobotsDoc {
    let mut groups: Vec<Group> = Vec::new();
    let mut current: Option<Group> = None;
    // True once a rule line has been seen for `current`: the *next*
    // `User-agent:` line then starts a new group instead of extending this
    // one, per RFC 9309's "consecutive User-agent lines" rule.
    let mut current_has_rules = false;

    for raw_line in body.lines() {
        let line = raw_line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let Some((key, value)) = line.split_once(':') else {
            continue;
        };
        let key = key.trim().to_ascii_lowercase();
        let value = value.trim();
        match key.as_str() {
            "user-agent" => {
                let token = value.to_ascii_lowercase();
                if token.is_empty() {
                    continue;
                }
                if current_has_rules || current.is_none() {
                    if let Some(g) = current.take() {
                        groups.push(g);
                    }
                    current = Some(Group::default());
                    current_has_rules = false;
                }
                current
                    .get_or_insert_with(Group::default)
                    .agents
                    .push(token);
            }
            "disallow" if !value.is_empty() => {
                if let Some(g) = current.as_mut() {
                    g.rules.push((value.to_string(), false));
                    current_has_rules = true;
                }
            }
            "allow" if !value.is_empty() => {
                if let Some(g) = current.as_mut() {
                    g.rules.push((value.to_string(), true));
                    current_has_rules = true;
                }
            }
            _ => {}
        }
    }
    if let Some(g) = current {
        groups.push(g);
    }
    RobotsDoc { groups }
}

/// Match a robots.txt path pattern (which may use `*` and a trailing `$`
/// anchor) against a request's path+query. The pattern always matches from
/// the start of the target — `Disallow: /a` matches `/a`, `/ab`, `/a/b`, but
/// not `/xa`.
fn matches_pattern(pattern: &str, target: &str) -> bool {
    let (body, anchored) = match pattern.strip_suffix('$') {
        Some(b) => (b, true),
        None => (pattern, false),
    };
    let mut segments = body.split('*');
    let first = segments.next().unwrap_or("");
    let Some(cursor) = target.strip_prefix(first) else {
        return false;
    };
    let rest: Vec<&str> = segments.collect();
    let mut cursor = cursor;
    for (i, seg) in rest.iter().enumerate() {
        if seg.is_empty() {
            continue; // consecutive '*' or a trailing bare '*'
        }
        let is_last = i == rest.len() - 1;
        if is_last && anchored {
            return cursor.ends_with(seg);
        }
        match cursor.find(seg) {
            Some(idx) => cursor = &cursor[idx + seg.len()..],
            None => return false,
        }
    }
    if anchored && rest.is_empty() {
        return cursor.is_empty();
    }
    true
}

/// Target string for matching: path, plus `?query` when present.
fn target_of(url: &Url) -> String {
    match url.query() {
        Some(q) => format!("{}?{q}", url.path()),
        None => url.path().to_string(),
    }
}

/// Per-origin cache shared across a run. Network fetches happen *outside*
/// the lock — only the map access is serialized — so a slow robots.txt fetch
/// for one host no longer blocks lookups for every other host (the previous
/// design wrapped the whole `is_allowed` call, network fetch included, in a
/// single `Mutex<RobotsChecker>` held by the caller).
#[derive(Default)]
pub struct RobotsChecker {
    cache: Mutex<HashMap<String, Option<Arc<RobotsDoc>>>>,
}

impl RobotsChecker {
    pub fn new() -> Self {
        Self::default()
    }

    /// Returns `Ok(true)` when the URL may be fetched. Lookup failures
    /// (missing robots.txt, network error) resolve to "allowed" — robots is
    /// advisory, never a reason to hard-fail an otherwise-good fetch.
    pub fn is_allowed(&self, http: &Http, url: &str) -> Result<bool> {
        let parsed =
            Url::parse(url).map_err(|e| Error::Config(format!("invalid URL '{url}': {e}")))?;
        let origin = ratelimit::origin_of(&parsed);
        let target = target_of(&parsed);

        let existing = {
            let guard = self.cache.lock().unwrap_or_else(|e| e.into_inner());
            guard.get(&origin).cloned()
        };
        let doc = match existing {
            Some(doc) => doc,
            None => {
                let fetched = self.fetch_rules(http, &origin).map(Arc::new);
                let mut guard = self.cache.lock().unwrap_or_else(|e| e.into_inner());
                guard.entry(origin).or_insert_with(|| fetched.clone());
                fetched
            }
        };
        Ok(doc
            .map(|d| d.is_allowed(PRODUCT_TOKEN, &target))
            .unwrap_or(true))
    }

    fn fetch_rules(&self, http: &Http, origin: &str) -> Option<RobotsDoc> {
        let url = Url::parse(&format!("{origin}/robots.txt")).ok()?;
        let body = http.get_text(url, MAX_ROBOTS_BYTES).ok()?;
        if body.status == 404 {
            return None;
        }
        Some(parse_robots(&body.text))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn allowed(doc: &RobotsDoc, path: &str) -> bool {
        doc.is_allowed(PRODUCT_TOKEN, path)
    }

    #[test]
    fn wildcard_group_only() {
        let body = "\
            User-agent: googlebot\n\
            Disallow: /no-bots\n\
            User-agent: *\n\
            Disallow: /private/\n\
            Disallow: /tmp\n\
            Allow: /private/open\n";
        let doc = parse_robots(body);
        assert!(allowed(&doc, "/public"));
        assert!(!allowed(&doc, "/private/secret"));
        assert!(!allowed(&doc, "/tmp/x"));
        assert!(allowed(&doc, "/private/open")); // allow beats disallow
    }

    #[test]
    fn consecutive_user_agent_lines_form_one_group_wildcard_first() {
        let body = "User-agent: *\nUser-agent: SomeBot\nDisallow: /private\n";
        let doc = parse_robots(body);
        assert!(!allowed(&doc, "/private/x"), "wildcard rules must survive");
    }

    #[test]
    fn consecutive_user_agent_lines_form_one_group_wildcard_last() {
        // The old bug only "worked" in this order by accident; must hold
        // both ways now.
        let body = "User-agent: SomeBot\nUser-agent: *\nDisallow: /private\n";
        let doc = parse_robots(body);
        assert!(!allowed(&doc, "/private/x"));
    }

    #[test]
    fn non_consecutive_groups_for_the_same_token_are_merged() {
        // Two separate `User-agent: *` blocks, interleaved with an unrelated
        // bot's group — a common shape when a robots.txt is assembled by
        // appending a plugin's rules to a hand-written file. Both `*` blocks
        // must apply; picking only the first one found would silently allow
        // whatever the second block disallows.
        let body = "\
            User-agent: *\n\
            Disallow: /a\n\
            User-agent: GPTBot\n\
            Disallow: /gpt-only\n\
            User-agent: *\n\
            Disallow: /b\n";
        let doc = parse_robots(body);
        assert!(!allowed(&doc, "/a/x"), "first * group must still apply");
        assert!(!allowed(&doc, "/b/x"), "second * group must also apply");
        assert!(allowed(&doc, "/c"));
    }

    #[test]
    fn non_consecutive_groups_for_our_own_token_are_also_merged() {
        let body = "\
            User-agent: webseek\n\
            Disallow: /a\n\
            User-agent: OtherBot\n\
            Disallow: /other-only\n\
            User-agent: webseek\n\
            Allow: /a/exception\n";
        let doc = parse_robots(body);
        assert!(!allowed(&doc, "/a/secret"));
        assert!(allowed(&doc, "/a/exception"));
    }

    #[test]
    fn our_own_product_token_takes_priority_over_wildcard() {
        let body = "\
            User-agent: *\n\
            Disallow: /\n\
            User-agent: webseek\n\
            Allow: /\n";
        let doc = parse_robots(body);
        // Everyone else is blocked, but webseek has its own group.
        assert!(allowed(&doc, "/anything"));
    }

    #[test]
    fn a_specific_group_for_someone_else_does_not_affect_us() {
        let body = "User-agent: GPTBot\nDisallow: /\n";
        let doc = parse_robots(body);
        // No `*` group and no `webseek` group -> unrestricted for us.
        assert!(allowed(&doc, "/anything"));
    }

    #[test]
    fn inline_comments_are_stripped_before_parsing() {
        let doc = parse_robots("User-agent: *\nDisallow: /private # internal only\n");
        // The rule value must end up as exactly "/private": a normal path
        // that merely starts with it is blocked (ordinary prefix matching)...
        assert!(!allowed(&doc, "/private"));
        assert!(!allowed(&doc, "/private/page"));
        // ...while an unrelated path is not, which would NOT hold if the
        // comment had leaked into the pattern (the rule would then be the
        // much longer, near-unmatchable literal "/private # internal only").
        assert!(allowed(&doc, "/public"));
    }

    #[test]
    fn full_line_comments_and_empty_lines_are_ignored() {
        let doc = parse_robots("# comment\n\nUser-agent: *\n# inner\nDisallow: /x\n");
        assert!(!allowed(&doc, "/x/1"));
        assert!(allowed(&doc, "/y"));
    }

    #[test]
    fn longest_match_wins_and_allow_wins_ties() {
        let doc = parse_robots("User-agent: *\nDisallow: /a\nAllow: /a/b\n");
        assert!(!allowed(&doc, "/a/c"));
        assert!(allowed(&doc, "/a/b/c"));
        let tie = parse_robots("User-agent: *\nDisallow: /a\nAllow: /a\n");
        assert!(allowed(&tie, "/a"));
    }

    #[test]
    fn wildcard_and_end_anchor_are_supported() {
        let doc = parse_robots("User-agent: *\nDisallow: /*.pdf$\n");
        assert!(!allowed(&doc, "/docs/report.pdf"));
        assert!(allowed(&doc, "/docs/report.pdf.html"));
        assert!(allowed(&doc, "/docs/index.html"));
    }

    #[test]
    fn query_parameters_are_evaluated() {
        let doc = parse_robots("User-agent: *\nDisallow: /*?download=\n");
        assert!(!allowed(&doc, "/file?download=1"));
        assert!(allowed(&doc, "/file?view=1"));
        assert!(allowed(&doc, "/file"));
    }

    #[test]
    fn target_of_includes_query_string() {
        let url = Url::parse("https://example.com/file?download=1&x=2").unwrap();
        assert_eq!(target_of(&url), "/file?download=1&x=2");
        let url = Url::parse("https://example.com/file").unwrap();
        assert_eq!(target_of(&url), "/file");
    }

    #[test]
    fn no_rules_means_allowed() {
        let doc = parse_robots("");
        assert!(allowed(&doc, "/"));
    }

    #[test]
    fn disallow_root_blocks_everything() {
        let doc = parse_robots("User-agent: *\nDisallow: /\n");
        assert!(!allowed(&doc, "/"));
        assert!(!allowed(&doc, "/anything/at/all"));
    }
}
